import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync(new URL("../outputs/bowling-drill-3d-prototype.html", import.meta.url), "utf8");

assert.match(html, /登録者名簿/, "roster title must be visible");
assert.match(html, /id="profileRosterCount"/, "roster count must be present");
assert.match(html, /氏名<\/span><span>利き手<\/span><span>投球<\/span><span>更新日/, "roster columns must be present");
assert.doesNotMatch(html, /if \(!query\) \{\s*results\.innerHTML = ""/, "empty query must not hide the roster");
assert.match(html, /window\.confirm\(`\$\{label\} の保存データを削除します/, "delete must require confirmation");
assert.match(html, /function profileRosterData\(/, "roster row formatter must exist");
assert.match(html, /role="option" aria-selected=/, "selection state must be exposed accessibly");
assert.match(html, /data-profile-view="lookup"/, "app must start in lookup view");
assert.match(html, /function setProfileView\(view\)/, "workflow view controller must exist");
assert.match(html, /id="registerProfile"/, "registration must have an explicit completion action");
assert.match(html, /id="registerProfile" type="button">登録<\/button>/, "registration action must be labelled only as registration");
assert.doesNotMatch(html, /登録してメジャーシートへ|更新してメジャーシートへ/, "registration screen must not combine registration and navigation in one label");
assert.match(html, /id="quickSaveProfile"/, "measure view must expose a visible save action");
assert.match(html, /setProfileView\("measure"\)/, "loading or registering must enter measure view");
assert.match(html, /id="backToProfileLookup"/, "measure view must return to roster");
assert.match(html, /function profileSearchText\(/, "expanded personal information must be searchable");
assert.match(html, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/, "registration form must use a balanced two-column grid");
assert.match(html, /\.profile-editor > \.control-group-note/, "registration guidance must span the form width");
assert.match(html, /\.profile-registration-actions \{ grid-template-columns: repeat\(2/, "two registration actions must fill the complete row");
assert.match(html, /class="profile-form-heading">基本情報/, "registration form must group basic information");
assert.match(html, /class="profile-form-heading">連絡情報/, "registration form must group contact information");

assert.match(html, /body\[data-profile-view="lookup"\],\s*body\[data-profile-view="register"\][\s\S]*?min-height: 100vh/, "entry views must occupy a standalone page");
assert.match(html, /body\[data-profile-view="lookup"\] \.app,[\s\S]*?height: auto;[\s\S]*?overflow: visible;/, "entry views must not retain the fixed measure workspace viewport");
assert.match(html, /この画面では個人情報のみを登録します。/, "registration screen must state its personal-information-only scope");
assert.match(html, /person,[\s\S]*?measure: \{ ranges, selects, checks, catalogs \}/, "personal and measure data must be stored in separate objects");
assert.match(html, /measure: existingProfile \? profileMeasure\(existingProfile\) : null/, "personal registration must not create measure data");
assert.match(html, /handedness: selectValue\("handedness"\)/, "handedness must belong to personal information");
assert.match(html, /bowlingStyle: selectValue\("bowlingStyle"\)/, "bowling style must belong to personal information");
assert.match(html, /\["profileList", "handedness", "bowlingStyle", "twoHandThumbUse"\]\.includes\(select\.id\)/, "personal attributes must be excluded from measure data");
assert.match(html, /function enforceProfileViewBoundary\(\)/, "entry view must enforce a structural visibility boundary");
assert.match(html, /\.app > aside > :not\(\.data-section\), \.right-workspace/, "all non-personal workspace regions must be structurally hidden in entry views");
assert.match(html, /display: none !important;/, "late measure-sheet display rules must not override the entry boundary");
assert.match(html, /profileBoundaryObserver\.observe\(profileAside, \{ childList: true \}\)/, "dynamically relocated measure panels must remain behind the entry boundary");
assert.match(html, /\.profile-context-bar \{[\s\S]*?grid-column: 1 \/ -1;/, "active-person context must span the full panel width");
assert.match(html, /\.profile-context-actions button \{[\s\S]*?white-space: nowrap;/, "active-person actions must not wrap vertically");
assert.match(html, /\.profile-context-actions \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/, "active-person actions must use equal-width buttons");
assert.match(html, /if \(measuring\) refreshMeasureWorkspace\(\)/, "entering the measure view must refresh its viewport");
assert.match(html, /function refreshMeasureWorkspace\(\)[\s\S]*?requestAnimationFrame[\s\S]*?resizeCanvas\(\);[\s\S]*?draw\(\);/, "3D redraw must wait for the revealed layout and resize the canvas");
assert.match(html, /const modelViewportObserver = new ResizeObserver/, "3D viewport must react to post-transition size changes");
assert.match(html, /class="right-modeling-controls">[\s\S]*?personal-axis-panel[\s\S]*?drill-layout-panel/, "PAP panel must be above the drill-layout panel on the right");
assert.match(html, /id="thumbSolidModeSheet"/, "measure sheet must expose the thumb-solid on/off choice");
assert.match(html, /#thumbSolidModeSheet[\s\S]*?source\.dispatchEvent\(new Event\("change"/, "measure-sheet thumb-solid choice must update the model source");
assert.match(html, /aside > \.measure-section \.measure-diagram svg \{[\s\S]*?opacity: \.34;/, "measure connectors must remain visually subordinate to controls");
assert.match(html, /id="measureHoleConnectors" class="measure-hole-connectors"/, "hole connectors must use a dedicated responsive SVG layer");
assert.doesNotMatch(html, /marker-start=|marker-end=|id="measureArrow"/, "hole connectors must be plain lines without arrowheads");
assert.match(html, /const circleEdgeSegment = \(from, to\)/, "connector endpoints must be calculated from circle geometry");
assert.match(html, /from\.x \+ ux \* from\.radius[\s\S]*?to\.x - ux \* to\.radius/, "connectors must run from circle edge to circle edge");
assert.match(html, /\.measure-depth-middle,[\s\S]*?top: 31%;[\s\S]*?\.measure-pitch-control\.measure-pitch-middle,[\s\S]*?top: 40%;/, "finger pitch controls must align beside desktop hole controls with depth above");
assert.match(html, /field-middle-hole,[\s\S]*?field-ring-hole \{ top: 37%;[\s\S]*?measure-pitch-control\.measure-pitch-ring \{ top: 37%;/, "responsive finger pitch controls must share the hole-size centerline");
assert.match(html, /\.measure-depth-middle,[\s\S]*?\.measure-pitch-control\.measure-pitch-middle[\s\S]*?left: 18%;/, "finger depth and pitch controls must share one vertical column");
assert.match(html, /field-main-span,[\s\S]*?top: 63\.5%;[\s\S]*?field-thumb-hole \{ top: 76%;/, "span and thumb regions must leave clearance below pitch controls");
assert.match(html, /measure-depth-middle,[\s\S]*?measure-pitch-control\.measure-pitch-middle[\s\S]*?left: 15%;/, "desktop finger depth and pitch controls must share one vertical column");
assert.match(html, /aside > \.measure-section \.measure-diagram \{[\s\S]*?height: 1300px;/, "desktop measure sheet must provide enough vertical clearance");
assert.match(html, /field-thumb-hole button::after[\s\S]*?font-size: 22px;[\s\S]*?transform: translateY\(-1px\)/, "all circular plus/minus glyphs must use one optically centered size");
assert.match(html, /button\[data-step="1"\]::after \{ content: "\+"; \}/, "circular plus controls must use a normalized glyph");
assert.match(html, /button\[data-step="-1"\]::after \{ content: "−"; \}/, "circular minus controls must use a normalized glyph");
assert.match(html, /\.thumb-accessory-group \{[\s\S]*?left: 50%;[\s\S]*?grid-template-columns: 190px 166px 190px;/, "thumb outer diameter must occupy the center column of a symmetric grid");
assert.match(html, /measure-sheet-control\.field-thumb-solid \{[\s\S]*?grid-column: 2;/, "thumb outer diameter must stay on the sheet centerline");
assert.match(html, /group\.append\(mode, solidCaption, solidControl, depth\)/, "thumb mode, outer diameter, and depth must be grouped structurally");

console.log("profile workflow tests: 59 passed");
